### ISSUE TITLE
Error al generar certificado en Vagrant

### ISSUE THREAD

**Issue by migromarj** [innosoft-innoweb/innosoft-innoweb-1#89]
Al revisar la pull request #83 se ha detectado un error relacionado con el generador de certificados.

Para reproducir el error siga los siguiente pasos:

- Pulse sobre la imagen de cualquier avatar que se encuentre en el *podium* general.
- Haga scroll hasta llegar al apartado de eventos en los que ha participado el usuario.
- Pulse sobre el botón *Descargar* de cualquier evento.

Al seguir todos los pasos descritos anteriormente, debe aparecer el siguiente error:

![207683880-d573b331-7766-4d0a-be22-15a6f3d07bdc](https://user-images.githubusercontent.com/80202474/207705254-a026d097-7f74-45be-bc64-ef2aa39005bd.png)

El comportamiento esperado sería obtener la imagen del certificado al pulsar sobre el botón *Descargar* de cualquier evento.

El error ha sido producido cuando se ha intentado visualizar la aplicación ejecutándose con Vagrant en Ubuntu 20.04, en un equipo host con Windows 10, usando el navegador Google Chrome versión 108.0.5359.100.

Se cree que el error es debido al uso de '\' en la ruta usada para hacer referencia a la imagen del certificado.

**Comment by IsmaelP19** [comment]
Se ha detectado el mismo error en main cuando se ha comprobado el funcionamiento con Docker.
Aparentemente, se ha sobrescrito el cambio de la ruta sustituyéndose por la ruta anterior conflictiva.

**Comment by TomasCB24** [comment]
Lo siento, he vuelto a comprobar y me da un error al querer ver un certificado. Creo que es por el response del método.
