### ISSUE TITLE
Bug en fichero docker-compose.yml

### ISSUE THREAD

**Issue by migromarj** [innosoft-innoweb/innosoft-innoweb-1#91]
Al configurar el despliegue continuo de Docker en la pull request #85 se definió que al hacer el build y el push de la imagen la tag se cogería automáticamente, dado que este workflow está configurado únicamente para que se ejecute en main siempre se hará un push con la etiqueta _main_.

Se ha detectado un fallo en el archivo [docker-compose.yml](https://github.com/innosoft-innoweb/innosoft-innoweb-1/blob/main/docker-compose.yml), dado que en este se indica que debe coger la imagen con etiqueta _latest_, como se puede observar en la siguiente imagen:

![image](https://user-images.githubusercontent.com/80202474/207893593-89a70e2c-b930-4709-9c48-9f3b58b46d5e.png)

El comportamiento esperado sería obtener la imagen de Docker con la etiqueta _main_.

**Comment by TomasCB24** [comment]
okey, lo cambio en un momento.
